package projectprogramming;

import com.placeholder.PlaceHolder;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;

/**
 *
 * @author Andry Kwiatow
 */
public class GUI extends javax.swing.JFrame {
    
    sqlConnection cnDB = new sqlConnection();
    Connection connnect = cnDB.connectionSql();
    public GUI() {
        initComponents();
        cnDB.connectionSql();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanelLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordUser = new javax.swing.JPasswordField();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonAppLogin = new javax.swing.JButton();
        btnLogin = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JLabel();
        jPanelSignUp = new javax.swing.JPanel();
        btnStudent = new javax.swing.JLabel();
        btnProfessor = new javax.swing.JLabel();
        jPanelRegister = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jPanelU_Data = new javax.swing.JPanel();
        jTextFieldF_Name = new javax.swing.JTextField();
        jTextFieldL_Name = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jComboBoxID_Type = new javax.swing.JComboBox();
        jTextFieldAccountType = new javax.swing.JTextField();
        jComboCity = new javax.swing.JComboBox();
        jComboDepartment = new javax.swing.JComboBox();
        jComboCarreer = new javax.swing.JComboBox();
        jLabelLCarreer = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelLName = new javax.swing.JLabel();
        jLabelID_Type = new javax.swing.JLabel();
        jLabelLCity1 = new javax.swing.JLabel();
        jPanelU_Login = new javax.swing.JPanel();
        jTextFieldUsernameR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jPasswordR = new javax.swing.JPasswordField();
        jPanelHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOGOTA'S UNIVERSITY");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        setForeground(java.awt.Color.black);
        setLocation(new java.awt.Point(200, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(740, 400));
        jPanelUser.setVisible(true);
        jPanelRegister.setVisible(false);

        jPanelUser.setBackground(new java.awt.Color(29, 185, 84));
        jPanelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/knowledge.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanelUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabelWelcome.setBackground(new java.awt.Color(40, 40, 40));
        jLabelWelcome.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(40, 40, 40));
        jLabelWelcome.setText("Welcome to Bogota's University login site");
        jPanelUser.add(jLabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 40));

        jLayeredPane2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLayeredPane2.setEnabled(false);
        jLayeredPane2.setVisible(false);
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogin.setBackground(new java.awt.Color(40, 40, 40));
        jPanelLogin.setVisible(false);
        jPanelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME:");
        jPanelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD:");
        jPanelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 30));

        jPasswordUser.setBackground(new java.awt.Color(22, 25, 36));
        jPasswordUser.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordUser.setText("jPasswordField1");
        jPasswordUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordUserActionPerformed(evt);
            }
        });
        jPanelLogin.add(jPasswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, 30));

        PlaceHolder txtHolder = new PlaceHolder(jTextFieldUsername,"Please insert your user");
        jTextFieldUsername.setBackground(new java.awt.Color(22, 25, 36));
        jTextFieldUsername.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldUsername.setToolTipText("");
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jPanelLogin.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 190, 30));

        jButtonAppLogin.setBackground(new java.awt.Color(29, 185, 84));
        jButtonAppLogin.setText("Login");
        jButtonAppLogin.setBorder(null);
        jButtonAppLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonAppLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 90, 40));

        jLayeredPane2.add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 310, 170));

        jPanelUser.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 740, 170));

        btnLogin.setBackground(new java.awt.Color(22, 25, 36));
        btnLogin.setForeground(new java.awt.Color(78, 78, 78));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("Login");
        btnLogin.setMaximumSize(null);
        btnLogin.setMinimumSize(null);
        btnLogin.setName(""); // NOI18N
        btnLogin.setOpaque(true);
        btnLogin.setPreferredSize(null);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        jPanelUser.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, 30));

        btnSignUp.setBackground(new java.awt.Color(22, 25, 36));
        btnSignUp.setForeground(new java.awt.Color(78, 78, 78));
        btnSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSignUp.setText("Sign Up");
        btnSignUp.setName(""); // NOI18N
        btnSignUp.setOpaque(true);
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        jPanelUser.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 160, 30));

        jPanelSignUp.setBackground(new java.awt.Color(40, 40, 40));
        jPanelSignUp.setVisible(false);
        jPanelSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/student_final.png"))); // NOI18N
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentMouseClicked(evt);
            }
        });
        jPanelSignUp.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/professor_final.png"))); // NOI18N
        btnProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfessorMouseClicked(evt);
            }
        });
        jPanelSignUp.add(btnProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jPanelUser.add(jPanelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 220, 140));

        jPanelRegister.setBackground(new java.awt.Color(0, 12, 64));
        jPanelRegister.setPreferredSize(new java.awt.Dimension(740, 400));
        jPanelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setPreferredSize(new java.awt.Dimension(740, 400));
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelU_Data.setBackground(new java.awt.Color(22, 25, 36));
        jPanelU_Data.setForeground(new java.awt.Color(0, 12, 65));
        jPanelU_Data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldF_Name.setBackground(new java.awt.Color(40, 40, 40));
        jTextFieldF_Name.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldF_Name.setText("Name");
        jTextFieldF_Name.setBorder(null);
        jTextFieldF_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldF_NameActionPerformed(evt);
            }
        });
        jPanelU_Data.add(jTextFieldF_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 230, 30));

        jTextFieldL_Name.setBackground(new java.awt.Color(40, 40, 40));
        jTextFieldL_Name.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldL_Name.setText("Lastname");
        jTextFieldL_Name.setBorder(null);
        jTextFieldL_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldL_NameActionPerformed(evt);
            }
        });
        jPanelU_Data.add(jTextFieldL_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 230, 30));

        jTextFieldID.setBackground(new java.awt.Color(40, 40, 40));
        jTextFieldID.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setText("jTextField3");
        jTextFieldID.setBorder(null);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jPanelU_Data.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, 20));

        jComboBoxID_Type.setBackground(new java.awt.Color(40, 40, 40));
        jComboBoxID_Type.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxID_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cédula Ciudadania", "Tarjeta de Identidad", "Cédula Extranjeria", "Pasaporte", "Registro Civil", " " }));
        jComboBoxID_Type.setBorder(null);
        jComboBoxID_Type.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelU_Data.add(jComboBoxID_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        jTextFieldAccountType.setBackground(new java.awt.Color(40, 40, 40));
        jTextFieldAccountType.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jTextFieldAccountType.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldAccountType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAccountType.setText("jTextField1");
        jTextFieldAccountType.setBorder(null);
        jPanelU_Data.add(jTextFieldAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 50));

        jComboCity.setBackground(new java.awt.Color(40, 40, 40));
        jComboCity.setForeground(new java.awt.Color(255, 255, 255));
        jComboCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bogotá", "Medellin", "Villavicencio", "Cali", "Pasto" }));
        jComboCity.setBorder(null);
        jPanelU_Data.add(jComboCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, -1));

        jComboDepartment.setBackground(new java.awt.Color(40, 40, 40));
        jComboDepartment.setForeground(new java.awt.Color(255, 255, 255));
        jComboDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bogotá D.C.", "Antioquia", "Meta", "Valle del Cauca", "Nariño" }));
        jComboDepartment.setBorder(null);
        jPanelU_Data.add(jComboDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 120, -1));

        jComboCarreer.setBackground(new java.awt.Color(40, 40, 40));
        jComboCarreer.setForeground(new java.awt.Color(255, 255, 255));
        jComboCarreer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingeniería de Sistemas ", "Ingeniería Electrónica", "Administración de Empresas", "Ciencias espaciales", " " }));
        jComboCarreer.setBorder(null);
        jPanelU_Data.add(jComboCarreer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 230, -1));

        jLabelLCarreer.setFont(new java.awt.Font("Dialog", 0, 7)); // NOI18N
        jLabelLCarreer.setForeground(new java.awt.Color(153, 153, 153));
        jLabelLCarreer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLCarreer.setText("Carreer");
        jLabelLCarreer.setToolTipText("");
        jPanelU_Data.add(jLabelLCarreer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 100, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 7)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Name");
        jLabel7.setToolTipText("");
        jPanelU_Data.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 60, -1));

        jLabelLName.setFont(new java.awt.Font("Dialog", 0, 7)); // NOI18N
        jLabelLName.setForeground(new java.awt.Color(153, 153, 153));
        jLabelLName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLName.setText("Lastname");
        jLabelLName.setToolTipText("");
        jPanelU_Data.add(jLabelLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, -1));

        jLabelID_Type.setFont(new java.awt.Font("Dialog", 0, 7)); // NOI18N
        jLabelID_Type.setForeground(new java.awt.Color(153, 153, 153));
        jLabelID_Type.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelID_Type.setText("Identification");
        jLabelID_Type.setToolTipText("");
        jPanelU_Data.add(jLabelID_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, -1));

        jLabelLCity1.setFont(new java.awt.Font("Dialog", 0, 7)); // NOI18N
        jLabelLCity1.setForeground(new java.awt.Color(153, 153, 153));
        jLabelLCity1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLCity1.setText("City / Department");
        jLabelLCity1.setToolTipText("");
        jPanelU_Data.add(jLabelLCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 100, -1));

        jLayeredPane3.add(jPanelU_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 400));

        jPanelU_Login.setBackground(new java.awt.Color(29, 185, 84));
        jPanelU_Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsernameR.setBackground(new java.awt.Color(40, 40, 40));
        jTextFieldUsernameR.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsernameR.setText("jTextField2");
        jTextFieldUsernameR.setBorder(null);
        jPanelU_Login.add(jTextFieldUsernameR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 120, 20));

        jLabel5.setBackground(new java.awt.Color(22, 25, 36));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        jPanelU_Login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 20));

        jLabel6.setBackground(new java.awt.Color(22, 25, 36));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");
        jPanelU_Login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, 20));

        jButtonRegister.setBackground(new java.awt.Color(22, 25, 36));
        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setText("Register");
        jButtonRegister.setToolTipText("");
        jButtonRegister.setBorder(null);
        jButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRegister.setName(""); // NOI18N
        jPanelU_Login.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, 60));

        jPasswordR.setBackground(new java.awt.Color(40, 40, 40));
        jPasswordR.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordR.setText("jPasswordField2");
        jPanelU_Login.add(jPasswordR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLayeredPane3.add(jPanelU_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 220, 400));

        jPanelRegister.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(50, 50, 50)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(166, 166, 166)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1.setLayer(jPanelUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelHome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordUserActionPerformed

    private void jTextFieldF_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldF_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldF_NameActionPerformed

    private void jTextFieldL_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldL_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldL_NameActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonAppLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAppLoginActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        btnLogin.setVisible(true);
        btnSignUp.setVisible(true);
        jPanelSignUp.setVisible(false);
        jPanelLogin.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseClicked
        jPanelUser.setVisible(false);
        jPanelRegister.setVisible(true);
    }//GEN-LAST:event_btnStudentMouseClicked

    private void btnProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfessorMouseClicked
        jPanelUser.setVisible(false);
        jPanelRegister.setVisible(true);
    }//GEN-LAST:event_btnProfessorMouseClicked

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setForeground(new java.awt.Color(120, 120, 120));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked

        //HEIGHT : 170 
        try{
            btnLogin.resize(btnLogin.getWidth(), 170);
            System.out.println("Login button height: " +  btnLogin.getHeight());
            jPanelLogin.setVisible(true);
            jLayeredPane2.setVisible(true);
            btnSignUp.setVisible(false);  
            btnLogin.repaint();
        }
        catch (Exception e){
            System.out.println("Error: " +  e.getMessage());
        }
        
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        jPanelSignUp.setVisible(true);
        jLayeredPane2.setVisible(true);
        jPanelLogin.setVisible(false);        
    }//GEN-LAST:event_btnSignUpMouseClicked

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        btnSignUp.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        btnSignUp.setForeground(new java.awt.Color(120, 120, 120));
    }//GEN-LAST:event_btnSignUpMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnLogin;
    public javax.swing.JLabel btnProfessor;
    public javax.swing.JLabel btnSignUp;
    public javax.swing.JLabel btnStudent;
    public javax.swing.JButton jButtonAppLogin;
    public javax.swing.JButton jButtonRegister;
    public javax.swing.JComboBox jComboBoxID_Type;
    public javax.swing.JComboBox jComboCarreer;
    public javax.swing.JComboBox jComboCity;
    public javax.swing.JComboBox jComboDepartment;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabelID_Type;
    public javax.swing.JLabel jLabelLCarreer;
    public javax.swing.JLabel jLabelLCity1;
    public javax.swing.JLabel jLabelLName;
    public javax.swing.JLabel jLabelWelcome;
    public javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JLayeredPane jLayeredPane2;
    public javax.swing.JLayeredPane jLayeredPane3;
    public javax.swing.JPanel jPanelHome;
    public javax.swing.JPanel jPanelLogin;
    public javax.swing.JPanel jPanelRegister;
    public javax.swing.JPanel jPanelSignUp;
    public javax.swing.JPanel jPanelU_Data;
    public javax.swing.JPanel jPanelU_Login;
    public javax.swing.JPanel jPanelUser;
    public javax.swing.JPasswordField jPasswordR;
    public javax.swing.JPasswordField jPasswordUser;
    public javax.swing.JTextField jTextFieldAccountType;
    public javax.swing.JTextField jTextFieldF_Name;
    public javax.swing.JTextField jTextFieldID;
    public javax.swing.JTextField jTextFieldL_Name;
    public javax.swing.JTextField jTextFieldUsername;
    public javax.swing.JTextField jTextFieldUsernameR;
    // End of variables declaration//GEN-END:variables
}
